package genres

// English names of the standard FB2 genres.
var namesEN = map[string]string{
	// Science fiction & fantasy
	"sf":                 "Science Fiction",
	"sf_action":          "Action SF",
	"sf_cyberpunk":       "Cyberpunk",
	"sf_detective":       "SF Detective",
	"sf_epic":            "Epic SF",
	"sf_fantasy":         "Fantasy",
	"sf_fantasy_city":    "Urban Fantasy",
	"sf_heroic":          "Heroic SF",
	"sf_history":         "Alternate History",
	"sf_horror":          "Horror & Mystic",
	"sf_humor":           "Humorous SF",
	"sf_postapocalyptic": "Post-Apocalyptic",
	"sf_social":          "Social SF",
	"sf_space":           "Space SF",
	"sf_stimpank":        "Steampunk",
	"sf_litrpg":          "LitRPG",
	"fantasy_fight":      "Battle Fantasy",
	"love_sf":            "Romantic SF",
	"popadanec":          "Portal Fiction",
	// Detectives & thrillers
	"detective":           "Detective",
	"det_action":          "Action",
	"det_classic":         "Classic Detective",
	"det_crime":           "Crime Fiction",
	"det_espionage":       "Spy Fiction",
	"det_hard":            "Hard-Boiled",
	"det_history":         "Historical Mystery",
	"det_irony":           "Ironic Mystery",
	"det_political":       "Political Thriller",
	"det_police":          "Police Procedural",
	"det_maniac":          "Serial Killer Fiction",
	"thriller":            "Thriller",
	"thriller_psychology": "Psychological Thriller",
	// Prose
	"prose":              "Prose",
	"prose_classic":      "Classic Prose",
	"prose_contemporary": "Contemporary Prose",
	"prose_counter":      "Counterculture",
	"prose_history":      "Historical Fiction",
	"prose_military":     "War Fiction",
	"prose_rus_classic":  "Russian Classics",
	"prose_su_classics":  "Soviet Classics",
	"great_story":        "Novel",
	"short_story":        "Short Story",
	"humor_prose":        "Humorous Prose",
	"humor":              "Humor",
	"aphorisms":          "Aphorisms",
	// Romance
	"love":              "Romance",
	"love_contemporary": "Contemporary Romance",
	"love_detective":    "Romantic Suspense",
	"love_erotica":      "Erotica",
	"love_history":      "Historical Romance",
	"love_short":        "Short Romance",
	// Adventure
	"adventure":    "Adventure",
	"adv_animal":   "Animal Stories",
	"adv_geo":      "Travel & Geography",
	"adv_history":  "Historical Adventure",
	"adv_indian":   "Western & Native American",
	"adv_maritime": "Sea Adventure",
	"adv_western":  "Western",
	// Children
	"children":        "Children's Literature",
	"child_adv":       "Children's Adventure",
	"child_det":       "Children's Mystery",
	"child_education": "Children's Education",
	"child_prose":     "Children's Prose",
	"child_sf":        "Children's SF",
	"child_tale":      "Fairy Tales",
	"child_verse":     "Children's Verse",
	"prose_game":      "Games & Activities",
	// Poetry & drama
	"poetry":     "Poetry",
	"dramaturgy": "Drama",
	"fable":      "Fables",
	"vers_libre": "Free Verse",
	// Antique
	"antique":          "Antique Literature",
	"antique_ant":      "Ancient Literature",
	"antique_east":     "Old Eastern Literature",
	"antique_european": "Old European Literature",
	"antique_myths":    "Myths & Legends",
	"antique_russian":  "Old Russian Literature",
	"folklore":         "Folklore",
	// Science & education
	"science":        "Science",
	"sci_biology":    "Biology",
	"sci_chem":       "Chemistry",
	"sci_culture":    "Cultural Studies",
	"sci_history":    "History",
	"sci_juris":      "Law",
	"sci_linguistic": "Linguistics",
	"sci_math":       "Mathematics",
	"sci_medicine":   "Medicine",
	"sci_philosophy": "Philosophy",
	"sci_phys":       "Physics",
	"sci_politics":   "Politics",
	"sci_psychology": "Psychology",
	"sci_religion":   "Religious Studies",
	"sci_tech":       "Technology",
	"sci_economy":    "Economics",
	// Nonfiction
	"nonfiction":     "Nonfiction",
	"nonf_biography": "Biography & Memoirs",
	"nonf_criticism": "Criticism",
	"nonf_publicism": "Essays & Journalism",
	"nonf_military":  "Military Nonfiction",
	"design":         "Art & Design",
	// Religion
	"religion":           "Religion",
	"religion_esoterics": "Esoterics",
	"religion_orthodoxy": "Orthodoxy",
	"religion_rel":       "Religious Literature",
	"religion_self":      "Self-Improvement",
	// Home & reference
	"home":           "Home & Family",
	"home_cooking":   "Cooking",
	"home_crafts":    "Hobbies & Crafts",
	"home_diy":       "Do It Yourself",
	"home_entertain": "Entertainment",
	"home_garden":    "Garden",
	"home_health":    "Health",
	"home_pets":      "Pets",
	"home_sex":       "Family Relations",
	"home_sport":     "Sports",
	"reference":      "Reference",
	"ref_dict":       "Dictionaries",
	"ref_encyc":      "Encyclopedias",
	"ref_guide":      "Guides",
	"ref_ref":        "Reference Books",
	// Computers & business
	"computers":        "Computers",
	"comp_db":          "Databases",
	"comp_hard":        "Hardware",
	"comp_osnet":       "OS & Networks",
	"comp_programming": "Programming",
	"comp_soft":        "Software",
	"comp_www":         "Internet",
	"economics":        "Business",
	"job_hunting":      "Job Hunting & Careers",
	"marketing":        "Marketing & Advertising",
	"banking":          "Finance",
	"accounting":       "Accounting & Taxes",
	"global_economy":   "Foreign Trade",
	"paper_work":       "Paperwork",
	"org_behavior":     "Management",
	"personal_finance": "Personal Finance",
	"real_estate":      "Real Estate",
	"small_business":   "Small Business",
	"stock":            "Securities",
	"trade":            "Trade",
	// Misc
	"periodic":           "Periodicals",
	"unrecognised":       "Uncategorized",
	"other":              "Other",
	"network_literature": "Web Fiction",
	"fanfiction":         "Fan Fiction",
}
